# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8441bd6ae37ed0cf2e8a5bef10706c4d5deef2e56a471ad0c7579c5e2481d5b2c895731e085dc51cbadd8dfbd1aae0b8effbe46095d27a8acc93b49759b7cff4

test:
  secret_key_base: bd60a7c8d2cbfad970f256740d62e248d168cba78d6b8fee6c2af6d4a4662b63908987281c1a1c2eb745ab1cdcc46868bb250cd45436c3771df88998d6093519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
