# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 636a86de58d9457231bcb4ba32dbd4875b44bf7fd21b9e097008d3c787138f4f54b2c11ca1bdacb4c23278991d84b88e3b3ff4d469788d093b86d580dfb481a6

test:
  secret_key_base: 1ec2c450f4a7faca3955755e1709cc63ad9ab9fa2c07854b2cf754890178e2ad4f4e7e36ea1438594b3fc291bb9b0b4cb4a9cbf7f51c252577f1e340982a2afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
